spring.profiles.active=dev
spring.application.name=streaming
server.port=8081
server.servlet.context-path=/streaming/api

# OpenAI Chat Model (non-streaming)
langchain4j.open-ai.chat-model.model-name=gpt-4o-mini

# OpenAI Streaming Chat Model
langchain4j.open-ai.streaming-chat-model.model-name=gpt-4o-mini

